<Project Sdk="Microsoft.NET.Sdk.BlazorWebAssembly">

  <PropertyGroup>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <WasmEmitTypeScriptDefinitions>true</WasmEmitTypeScriptDefinitions>
    
    <!-- Static Web Assets Fallback Enabled -->
    <StaticWebAssetSpaFallbackEnabled>true</StaticWebAssetSpaFallbackEnabled>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="BlazorMonaco" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly"/>
    <PackageReference Include="Microsoft.AspNetCore.Components.Gateway"/>
    <PackageReference Include="Microsoft.FluentUI.AspNetCore.Components" VersionOverride="5.0.0-rc.5-26219.1" />
    <PackageReference Include="Microsoft.FluentUI.AspNetCore.Components.Icons" VersionOverride="5.0.0-rc.5-26219.1" />
  </ItemGroup>

</Project>
