<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    <CentralPackageTransitivePinningEnabled>true</CentralPackageTransitivePinningEnabled>
    <!-- We are not using package source mapping. -->
    <NoWarn>$(NoWarn);NU1507</NoWarn>
    <NetCoreVersion>11.0.0-rc.1.26425.128</NetCoreVersion>
    <AspNetCoreVersion>$(NetCoreVersion)</AspNetCoreVersion>
    <RoslynBuild>26459.1</RoslynBuild>
    <RoslynVersion>5.12.0-1.$(RoslynBuild)</RoslynVersion>
    <RazorVersion>11.1.0-preview.$(RoslynBuild)</RazorVersion>
    <FluentUIVersion>4.14.4</FluentUIVersion>
    <NuGetVersion>7.9.0</NuGetVersion>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="AwesomeAssertions" Version="9.6.0" />
    <!-- When updating BlazorMonaco, check that VIM mode works. See https://github.com/jjonescz/DotNetLab/pull/57. -->
    <PackageVersion Include="BlazorMonaco" Version="3.5.0" />
    <PackageVersion Include="Combinatorial.MSTest" Version="2.0.0" />
    <PackageVersion Include="Humanizer.Core" Version="3.0.10" />
    <PackageVersion Include="ICSharpCode.Decompiler" Version="11.0.0.9375" />
    <PackageVersion Include="Knapcode.MiniZip" Version="0.21.1" />
    <PackageVersion Include="MetadataReferenceService.BlazorWasm" Version="0.0.1" />
    <PackageVersion Include="Microsoft.AspNetCore.App.Ref" Version="$(AspNetCoreVersion)" />
    <PackageVersion Include="Microsoft.AspNetCore.Components.Gateway" Version="$(AspNetCoreVersion)" />
    <PackageVersion Include="Microsoft.AspNetCore.Components.Web" Version="$(AspNetCoreVersion)" />
    <PackageVersion Include="Microsoft.AspNetCore.Components.WebAssembly" Version="$(AspNetCoreVersion)" />
    <PackageVersion Include="Microsoft.AspNetCore.Components.WebAssembly.Server" Version="$(AspNetCoreVersion)" />
    <PackageVersion Include="Microsoft.CodeAnalysis.CSharp" Version="$(RoslynVersion)" />
    <PackageVersion Include="Microsoft.CodeAnalysis.CSharp.CodeStyle" Version="$(RoslynVersion)" />
    <PackageVersion Include="Microsoft.CodeAnalysis.CSharp.Features" Version="$(RoslynVersion)" />
    <PackageVersion Include="Microsoft.CodeAnalysis.CSharp.Scripting" Version="$(RoslynVersion)" />
    <PackageVersion Include="Microsoft.CodeAnalysis.VisualBasic.Features" Version="$(RoslynVersion)" />
    <PackageVersion Include="Microsoft.DotNet.Arcade.Sdk" Version="9.0.0-beta.24372.7" />
    <PackageVersion Include="Microsoft.Extensions.Logging" Version="$(NetCoreVersion)" />
    <!--
    <PackageVersion Include="Microsoft.FluentUI.AspNetCore.Components" Version="$(FluentUIVersion)" />
    <PackageVersion Include="Microsoft.FluentUI.AspNetCore.Components.Icons" Version="$(FluentUIVersion)" />
    -->
    <PackageVersion Include="Microsoft.FluentUI.AspNetCore.Components" Version="5.0.0-rc.5-26219.1" />
    <PackageVersion Include="Microsoft.FluentUI.AspNetCore.Components.Icons" Version="5.0.0-rc.5-26219.1" />
    <PackageVersion Include="Microsoft.Net.Compilers.Razor.Toolset" Version="$(RazorVersion)" />
    <PackageVersion Include="Microsoft.Net.Compilers.Toolset" Version="$(RoslynVersion)" />
    <PackageVersion Include="Microsoft.NET.Test.Sdk" Version="18.10.0" />
    <PackageVersion Include="Microsoft.NETCore.App.Ref" Version="$(NetCoreVersion)" />
    <PackageVersion Include="Microsoft.TeamFoundationServer.Client" Version="20.256.2" />
    <PackageVersion Include="NuGet.Resolver" Version="$(NuGetVersion)" />
    <PackageVersion Include="NuGet.Versioning" Version="$(NuGetVersion)" />
    <PackageVersion Include="PolyType" Version="1.4.1" />
    <PackageVersion Include="protobuf-net" Version="3.4.21" />
    <PackageVersion Include="protobuf-net.BuildTools" Version="3.3.8" />
    <PackageVersion Include="Roslyn.Diagnostics.Analyzers" Version="$(RoslynVersion)" />
    <PackageVersion Include="System.IO.Hashing" Version="$(NetCoreVersion)" />
    <PackageVersion Include="Verify.MSTest" Version="32.0.0" />
  </ItemGroup>
  <ItemGroup Label="Pinned Transitive Dependencies">
    <PackageVersion Include="System.Drawing.Common" Version="5.0.3" />
    <PackageVersion Include="System.Security.Cryptography.Xml" Version="6.0.2" />
  </ItemGroup>
  <ItemGroup Label="Avoid warning MSB3277 (conflicts between different versions)">
    <PackageVersion Include="Microsoft.Bcl.AsyncInterfaces" Version="$(NetCoreVersion)" />
    <PackageVersion Include="Microsoft.Extensions.ObjectPool" Version="$(NetCoreVersion)" />
  </ItemGroup>
</Project>